{% set name = "CV-analysis" %}
{% set version = "0.1.6a" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  # url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip
  path: .

build:
  noarch: python
  number: 0
  entry_points:
    - testapp = cvanalysis.main:run_application



requirements:
  host:
    - python>=3.8
    - pip
    - setuptools

  run:
    - python>=3.8
    - numpy
    - pandas>=1.3.0
    - scipy
    - matplotlib
    - ges-echem-suite
    - pyqt

app:
  entry: testapp

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem